// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2rMB8gyCuOAT_EoFfY8UGmZcTjhUd8OU',
    appId: '1:972703181172:web:79774d82743890164fe421',
    messagingSenderId: '972703181172',
    projectId: 'edu-mobile-d35dd',
    authDomain: 'edu-mobile-d35dd.firebaseapp.com',
    databaseURL: 'https://edu-mobile-d35dd-default-rtdb.firebaseio.com',
    storageBucket: 'edu-mobile-d35dd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx59-dVQOZWRVd4wKYEgET2c6QQfWWScI',
    appId: '1:972703181172:android:9dc736a5013b0c8d4fe421',
    messagingSenderId: '972703181172',
    projectId: 'edu-mobile-d35dd',
    databaseURL: 'https://edu-mobile-d35dd-default-rtdb.firebaseio.com',
    storageBucket: 'edu-mobile-d35dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRzrtQZ_mlDa-Ix002V9P9wAvsdb17OxY',
    appId: '1:972703181172:ios:11659cb0fc9f95504fe421',
    messagingSenderId: '972703181172',
    projectId: 'edu-mobile-d35dd',
    databaseURL: 'https://edu-mobile-d35dd-default-rtdb.firebaseio.com',
    storageBucket: 'edu-mobile-d35dd.firebasestorage.app',
    iosBundleId: 'com.example.eduApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRzrtQZ_mlDa-Ix002V9P9wAvsdb17OxY',
    appId: '1:972703181172:ios:11659cb0fc9f95504fe421',
    messagingSenderId: '972703181172',
    projectId: 'edu-mobile-d35dd',
    databaseURL: 'https://edu-mobile-d35dd-default-rtdb.firebaseio.com',
    storageBucket: 'edu-mobile-d35dd.firebasestorage.app',
    iosBundleId: 'com.example.eduApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2rMB8gyCuOAT_EoFfY8UGmZcTjhUd8OU',
    appId: '1:972703181172:web:7afa16b159f349fc4fe421',
    messagingSenderId: '972703181172',
    projectId: 'edu-mobile-d35dd',
    authDomain: 'edu-mobile-d35dd.firebaseapp.com',
    databaseURL: 'https://edu-mobile-d35dd-default-rtdb.firebaseio.com',
    storageBucket: 'edu-mobile-d35dd.firebasestorage.app',
  );
}
